# name: Build and Deploy to Azure Web App

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup .NET
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: '9.0'             # or your target version

#       - name: Restore & Build
#         run: |
#           dotnet restore
#           dotnet build --configuration Release

#       - name: Publish artifact
#         run: dotnet publish -c Release -o publish

#       - name: 'Login via Azure CLI'
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: 'Deploy to Azure Web App'
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: ${{ secrets.AZURE_APP_NAME }}
#           slot-name: Production
#           package: ./publish
